pipeline {
    agent any

    environment {
        CONFIG_FILE = "python/pipeline-config/app.yaml"
    }

    stages {

        stage('Checkout') {
            steps {
                sh '''
                    rm -rf app-source || true
                    git clone /home/vansh.padia/Videos/DevSecops/python app-source
                '''
            }
        }

        stage('Load Config') {
            steps {
                script {
                    config = readYaml file: env.CONFIG_FILE

                    APP_TYPE = config.app.type
                    INSTALL_CMD = config.build.install
                    START_CMD = config.deploy.start

                    echo "Application Type: ${APP_TYPE}"
                }
            }
        }

        stage('Setup Runtime') {
            steps {
                sh """
                    chmod +x scripts/setup.sh
                    ./scripts/setup.sh ${APP_TYPE}
                """
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "${INSTALL_CMD}"
            }
        }

        stage('Deploy Application') {
            steps {
                sh """
                    chmod +x scripts/deploy.sh
                    ./scripts/deploy.sh "${START_CMD}"
                """
            }
        }

        stage('Health Check') {
            steps {
                sh "curl http://localhost:5000"
            }
        }
    }
}