rules:
  - id: high-confidence-secret-scan-v2
    category: general
    title: High-Confidence Secret Scan
    severity: HIGH
    path: .*\.(ya?ml|json)$  
    regex: '(?i)(?P<key>[a-z0-9_.-]{3,30})\s*[:=]\s*[''"]?(?P<secret>[a-zA-Z0-9@#$_%]{12,64})[''"]?'
    secret-group-name: secret
    allow-rules:
      - id: skip-known-safe-keys-v2
        description: "Allow common, non-secret configuration keys"
        # key: '(?i)^(title|description|format|output|adapter|database|severity|category|id|encoding|security-checks|ignore-unfixed|path)$'