.aws-cli:
  image: docker:25.0.5
  before_script:
    - apk update && apk upgrade
    - apk add --no-cache bash
    - apk add aws-cli
    - aws --version
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
